<?php
function dna_menu(){
    $items['dna'] = array(
        'title' => 'DNA Helix Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success_page'] = array(
        'title' => ' Helix Result',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form(){
    $form['dna_string'] = array(
        '#title' => ' DNA Strand',
        '#type' => 'textfield',
        '#description' => 'Enter a DNA Strand. You may only use A, T, C, or G.',
        '#element_validate' => array('element_validate_dna'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );
    return $form;
}

function element_validate_dna($element){
    $dna_input = str_split(strtolower($element['#value']));
    $accepted_values = array('a','c','g','t');
    foreach ($dna_input as $dna){
        if (!in_array($dna, $accepted_values)){
            form_error($element, t('Please only enter A, T, C, and G.'));
        }
    }
}
function dna($dna_strand){
    $nucleotides = str_split($dna_strand);
    $opposite_helix = array();

    foreach($nucleotides as $nucleotide){
        if($nucleotide == 'a'){
            $nucleotide = 't';
        } elseif($nucleotide == 't'){
            $nucleotide = 'a';
        } elseif ($nucleotide == 'g'){
            $nucleotide = 'c';
        } else{
            $nucleotide = 'g';
        }
        array_push($opposite_helix, $nucleotide);
    }
    $opposite_helix = strtoupper(implode($opposite_helix));
    return $opposite_helix;
}

function dna_form_submit($form, &$form_state){
    $dna_strand = strtolower($form_state['values']['dna_string']);
    $result = dna($dna_strand);
    $_SESSION['opposite_helix'] = $result;
    $_SESSION['original_helix'] = strtoupper($form_state['values']['dna_string']);
    $form_state['redirect'] = 'dna_success_page';
}

function dna_success(){
    $original = $_SESSION['original_helix'];
    $opposite = $_SESSION['opposite_helix'];
    return '<h3>Orginal Strand:</h3>' . '<p>' . $original . '</p>' . '<h3>Generated Strand:</h3>' . '<p>' . $opposite . '</p>';
}
