<?php
function dna_menu(){
    $items['dna'] = array(
        'title' => 'DNA Helix Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success_page'] = array(
        'name' => ' Helix Result',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form(){
    $form['dna_string'] = array(
        '#title' => ' DNA Strand',
        '#type' => 'textfield',
        '#description' => 'Enter a DNA Strand. You may only use A, T, C, or G.',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );
    return $form;
}

function dna_form_submit($form, &$form_state){
    $dna_strand = strtolower($form_state['values']['dna_string']);
    $nucleotides = str_split($dna_strand);
    $opposite_helix = array();

    foreach($nucleotides as $nucleotide){
        if($nucleotide == 'a'){
            $nucleotide = 't';
        } elseif($nucleotide == 't'){
            $nucleotide = 'a';
        } elseif ($nucleotide == 'g'){
            $nucleotide = 'c';
        } else{
            $nucleotide = 'g';
        }
        array_push($opposite_helix, $nucleotide);
    }
    $opposite_helix = implode($opposite_helix);
    $_SESSION['opposite_helix'] = $opposite_helix;
    $form_state['redirect'] = 'dna_success_page';
}

function dna_success(){
    $opposite = $_SESSION['opposite_helix'];
    return '<p>' . $opposite . '</p>';
}
